units:
  boots:
  - name: S2iCustomPy38Notebookv031Vuln0QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2170 - see https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv031Vuln1QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3058 - see https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv031Vuln2QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3576 - see https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv031Vuln3QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2717 - see https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv031Vuln4QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3816 - see https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv031Vuln7QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2569 - see https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv031Vuln8QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3582 - see https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv031Vuln10QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3075 - see https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv031Vuln13QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2574 - see https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv031Vuln16QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2354 - see https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv031Vuln22QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2575 - see https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv031Vuln27QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3057 - see https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv032Vuln0QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3816 - see https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv032Vuln1QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3057 - see https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv032Vuln2QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2574 - see https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv032Vuln3QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2717 - see https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv032Vuln4QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3576 - see https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv032Vuln5QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2170 - see https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv032Vuln6QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3058 - see https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv032Vuln8QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2354 - see https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv032Vuln11QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2569 - see https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv032Vuln13QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3582 - see https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv032Vuln17QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3075 - see https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv032Vuln27QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2575 - see https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv033Vuln0QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3816 - see https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv033Vuln2QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2354 - see https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv033Vuln3QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2575 - see https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv033Vuln5QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3576 - see https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv033Vuln6QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3057 - see https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv033Vuln7QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2170 - see https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv033Vuln8QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3058 - see https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv033Vuln9QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2717 - see https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv033Vuln10QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3582 - see https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv033Vuln12QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2574 - see https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv033Vuln13QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2569 - see https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv033Vuln16QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3075 - see https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv041Vuln0QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3816 - see https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv041Vuln1QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2569 - see https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv041Vuln2QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3582 - see https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv041Vuln4QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2574 - see https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv041Vuln5QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2354 - see https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv041Vuln6QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3576 - see https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv041Vuln9QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2575 - see https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv041Vuln10QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3075 - see https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv041Vuln13QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3057 - see https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv041Vuln16QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2717 - see https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv041Vuln24QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2170 - see https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv041Vuln25QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3058 - see https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv040Vuln0QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3816 - see https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv040Vuln2QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2170 - see https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv040Vuln3QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3058 - see https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv040Vuln4QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2574 - see https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv040Vuln6QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2569 - see https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv040Vuln8QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2354 - see https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv040Vuln9QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3576 - see https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv040Vuln12QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2717 - see https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv040Vuln15QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3582 - see https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv040Vuln19QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2575 - see https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv040Vuln24QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3057 - see https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv040Vuln25QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3075 - see https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv042Vuln0QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.2
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3816 - see https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv030Vuln0QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2574 - see https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv030Vuln1QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3582 - see https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv030Vuln2QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2717 - see https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv030Vuln3QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3057 - see https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv030Vuln5QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3816 - see https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv030Vuln7QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2575 - see https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv030Vuln8QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3576 - see https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv030Vuln11QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2354 - see https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv030Vuln14QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2569 - see https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv030Vuln18QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2170 - see https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv030Vuln19QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3058 - see https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv030Vuln20QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3075 - see https://access.redhat.com/errata/RHSA-2021:3075
  wraps:
  - name: S2iCustomPy38Notebookv031Vuln0QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv031Vuln1QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv031Vuln2QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv031Vuln3QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv031Vuln4QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv031Vuln7QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv031Vuln8QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv031Vuln10QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv031Vuln13QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv031Vuln16QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv031Vuln22QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv031Vuln27QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv032Vuln0QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv032Vuln1QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv032Vuln2QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv032Vuln3QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv032Vuln4QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv032Vuln5QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv032Vuln6QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv032Vuln8QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv032Vuln11QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv032Vuln13QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv032Vuln17QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv032Vuln27QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv033Vuln0QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv033Vuln2QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv033Vuln3QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv033Vuln5QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv033Vuln6QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv033Vuln7QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv033Vuln8QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv033Vuln9QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv033Vuln10QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv033Vuln12QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv033Vuln13QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv033Vuln16QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.3
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv041Vuln0QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv041Vuln1QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv041Vuln2QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv041Vuln4QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv041Vuln5QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv041Vuln6QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv041Vuln9QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv041Vuln10QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv041Vuln13QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv041Vuln16QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv041Vuln24QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv041Vuln25QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.1
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv040Vuln0QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv040Vuln2QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv040Vuln3QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv040Vuln4QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv040Vuln6QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv040Vuln8QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv040Vuln9QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv040Vuln12QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv040Vuln15QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv040Vuln19QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv040Vuln24QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv040Vuln25QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iCustomPy38Notebookv042Vuln0QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.4.2
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv030Vuln0QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iCustomPy38Notebookv030Vuln1QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iCustomPy38Notebookv030Vuln2QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iCustomPy38Notebookv030Vuln3QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iCustomPy38Notebookv030Vuln5QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iCustomPy38Notebookv030Vuln7QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iCustomPy38Notebookv030Vuln8QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iCustomPy38Notebookv030Vuln11QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iCustomPy38Notebookv030Vuln14QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iCustomPy38Notebookv030Vuln18QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iCustomPy38Notebookv030Vuln19QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iCustomPy38Notebookv030Vuln20QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-custom-py38-notebook:v0.3.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
