units:
  boots:
  - name: S2iJupyterbookv0130Vuln0QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3576 - see https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iJupyterbookv0130Vuln2QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2569 - see https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iJupyterbookv0130Vuln3QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3816 - see https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iJupyterbookv0130Vuln6QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3057 - see https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iJupyterbookv0130Vuln8QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2574 - see https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iJupyterbookv0130Vuln10QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3074' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3074
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3074 - see https://access.redhat.com/errata/RHSA-2021:3074
  - name: S2iJupyterbookv0130Vuln11QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3666' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3666
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3666 - see https://access.redhat.com/errata/RHSA-2021:3666
  - name: S2iJupyterbookv0130Vuln13QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2717 - see https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iJupyterbookv0130Vuln17QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3582 - see https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iJupyterbookv0130Vuln18QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2575 - see https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iJupyterbookv0130Vuln19QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2170 - see https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iJupyterbookv0130Vuln20QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3058 - see https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iJupyterbookv0130Vuln21QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:2354 - see https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iJupyterbookv0130Vuln24QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3075 - see https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iJupyterbookv0130Vuln35QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3073' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3073
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3073 - see https://access.redhat.com/errata/RHSA-2021:3073
  - name: S2iJupyterbookv0130Vuln36QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'RHSA-2021:3623' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3623
      not_acceptable: >-
        The base image used has a CVE RHSA-2021:3623 - see https://access.redhat.com/errata/RHSA-2021:3623
  wraps:
  - name: S2iJupyterbookv0130Vuln0QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3576' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3576
  - name: S2iJupyterbookv0130Vuln2QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2569' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2569
  - name: S2iJupyterbookv0130Vuln3QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3816' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3816
  - name: S2iJupyterbookv0130Vuln6QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3057' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3057
  - name: S2iJupyterbookv0130Vuln8QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2574' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2574
  - name: S2iJupyterbookv0130Vuln10QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3074' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3074
  - name: S2iJupyterbookv0130Vuln11QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3666' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3666
  - name: S2iJupyterbookv0130Vuln13QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2717' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2717
  - name: S2iJupyterbookv0130Vuln17QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3582' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3582
  - name: S2iJupyterbookv0130Vuln18QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2575' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2575
  - name: S2iJupyterbookv0130Vuln19QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2170' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2170
  - name: S2iJupyterbookv0130Vuln20QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3058' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3058
  - name: S2iJupyterbookv0130Vuln21QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:2354' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:2354
  - name: S2iJupyterbookv0130Vuln24QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3075' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3075
  - name: S2iJupyterbookv0130Vuln35QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3073' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3073
  - name: S2iJupyterbookv0130Vuln36QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-jupyterbook:v0.13.0
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'RHSA-2021:3623' in the base image used
        link: https://access.redhat.com/errata/RHSA-2021:3623
